[package]
name = "libremarkable"
version = "0.4.3"
authors = ["Can Selcik <contact@cselcik.com>"]
repository = "https://github.com/canselcik/libremarkable"
license = "MIT"
description = "The only publicly available Framework for developing applications for the Remarkable Paper Tablet w/ Low Latency Partial Refresh Support"
readme = "README.md"
exclude = [ "reference-material/*", "legacy-c-impl/*", "private/*" ]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
ioctl-gen = "0.1.1"
libc = "0.2.69"
mmap = "0.1.1"
rusttype = "0.8.2"
evdev = "0.11.0" # is https://github.com/emberian/evdev/pull/24 which re-fixes https://github.com/emberian/evdev/pull/23 which solves https://github.com/emberian/evdev/pull/22
nix = "0.20"
epoll = "4.1.0"
image = "0.21.3"
line_drawing = "0.8.0"
hlua = "0.4.1"
aabb-quadtree = "0.1.0"
zstd = "0.5.1"
stopwatch = "0.0.7"
atomic = { version = "0.5.0" }
cgmath = "0.17.0"
fxhash = "0.2.1"
lazy_static = "1.4.0"

[features]
enable-runtime-benchmarking = []

[profile.release]
debug = true
lto = true

[[example]]
name = "spy"
path = "examples/spy.rs"
crate-type = ["dylib"]

[[example]]
name = "demo"
path = "examples/demo.rs"
crate-type = ["bin"]

[[example]]
name = "live"
path = "examples/live.rs"
crate-type = ["bin"]

[dev-dependencies]
# For spy
redhook = "2.0.0"
libc = "0.2.69"
lazy_static = "1.4.0"
# For demo
chrono = "0.4.11"
# For live
tiny_http = "0.6.2"
